### PR TITLE
DOC: Refactor OpenAPI/Swagger aiohttp addons

### PR DESCRIPTION
**Pull request by socketpair**

### CODE REVIEW

**Comment by socketpair** [comment]
@asvetlov review

**Review by asvetlov — APPROVED** [review]
LGTM, please merge.
Backport to 3.8 is desirable as well

**Comment by socketpair** [comment]
@asvetlov how to make the backport ? new PR to another branch ?

**Comment by socketpair** [comment]
What to do so ?

**Comment by asvetlov** [comment]
`cherry_picker  19170e4 3.8`

Sorry for late reply.

**Comment by asvetlov** [comment]
Backported

**Pull request merged**
