### PR TITLE
Increase `base_protocol` coverage

### PR DESCRIPTION
**Pull request by amikrop**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Thanks

**Comment by Dreamsorcerer** [comment]
@webknjaz Patchback broke on this PR.

**Comment by Dreamsorcerer** [comment]
Nevermind, just redid the label and it sorted itself out.

**Comment by webknjaz** [comment]
Interesting... Sometimes GH API is flaky, and the bot doesn't do retries. Maybe that's why.

**Pull request merged**
