### PR TITLE
streams: block until n bytes read (#3681)

### PR DESCRIPTION
**Pull request by socketpair**
## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by kxepal** [comment]
This fixes what's case?

**Comment by socketpair** [comment]
@kxepal #3681

**Comment by socketpair** [comment]
I will write tests if concept is accepted.

**Comment by socketpair** [comment]
Well. Unittests test current implementation instead of specification, so it is expected that they will fail in many cases...

**Comment by asvetlov** [comment]
I've missed those read*() methods behavior.
Could you briefly summarize that should be in the end?

**Comment by Dreamsorcerer** [comment]
I think we'll close this one. The linked issue is already closed and the behaviour can be achieved with itertools, without forcing all users to have delayed chunks when they don't need full chunk sizes.

**Pull request closed without merging**
