### PR TITLE
replace freezegun with time_machine

### LINKED ISSUE #7655: Migrate to time-machine
It looks like freezegun is considered an abandoned project at this point.
We should look at migrating the tests to time-machine instead:
https://pypi.org/project/time-machine/

See, for example: https://github.com/spulec/freezegun/pull/511

### PR DESCRIPTION
**Pull request by gruebel**
## What do these changes do?

- replaced the `freezegun` dependency with `time-machine`, because it seems like `freezegun` became an unmaintained project

## Related issue number

Fixes #7655 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by gruebel** [comment]
@Dreamsorcerer looks like `time-machine` doesn't support `pypy` 😢 Do you have a specific way on handling such cases or should it be an other library altogether?

**Comment by Dreamsorcerer** [comment]
Ah, that's annoying. Not really sure what the best approach is...

**Comment by Dreamsorcerer** [comment]
Although, it looks like it's only used in 3 tests, so maybe we can just skip the tests on pypy for now...

**Comment by gruebel** [comment]
definitely a possibility, but I would also need to remove the dependency from the `test.in` file. Should I create a separate file, like `test_pypy.in` with the same constraint file as `test.in` and then I can do an if/else block in the workflow file to use the `pypy` flavour only, when `pypy` is tested?

**Comment by Dreamsorcerer** [comment]
> definitely a possibility, but I would also need to remove the dependency from the `test.in` file.

No, look at the mypy line in that file. You can do the same kind of thing to exclude installation on pypy.

**Comment by gruebel** [comment]
@Dreamsorcerer I think I added the needed changes 😅

**Comment by gruebel** [comment]
@Dreamsorcerer if you have time to take a look again, it would be great 🙂

**Comment by gruebel** [comment]
@Dreamsorcerer anything left to do here?

**Comment by Dreamsorcerer** [comment]
Sorry, just busy with 3.9 release tasks.

**Comment by Dreamsorcerer** [comment]
If you could handle that backport, that'd be great.

**Comment by gruebel** [comment]
sure, I will give it a try

**Pull request merged**
