### PR TITLE
DNM: Make get_extra_info calls lazy

### PR DESCRIPTION
**Pull request by bdraco**
Testing the performance of this change.  This may not work ok though since we might want to call them after the connection has been closed... but that probably doesn't make much sense

### CODE REVIEW

**Comment by bdraco** [comment]
make no difference

**Comment by bdraco** [comment]
Screenshot 2024-11-17 at 7 35 57 PM

Might be worth pursuing if it can be made to work

**Comment by bdraco** [comment]
looks like we have to save it in `__init__` just in case we might use it, sadly which is rare

**Comment by asvetlov** [comment]
> looks like we have to save it in `__init__` just in case we might use it, sadly which is rare

Exactly!
I didn't find a better way to save SSL info.
It is two dict lookups only internally though

**Comment by bdraco** [comment]
Yeah its pretty small on the profile so I threw it away pretty quickly as there are still better choices to optimize

**Pull request closed without merging**
