### PR TITLE
Remove sphinxcontrib-asyncio

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
I don't this is needed anymore, and may be causing issues with newer sphinx releases.

### CODE REVIEW

**Comment by webknjaz** [comment]
...maybe? I don't know what it does anyway.

**Review by webknjaz — APPROVED** [review]

**Comment by Dreamsorcerer** [comment]
Judging by the errors, it adds the `coroutine` directives. Updating them to `:async:`, which is what Sphinx itself uses these days.

**Comment by Dreamsorcerer** [comment]
@webknjaz If you've got a moment spare, could you take a look at the toctree and help decide what it should look like. In client.rst the default view now looks like:
image
I tried setting maxdepth to 3, which still looks a bit odd with duplicate headers:
https://aiohttp--7439.org.readthedocs.build/en/7439/client.html#aiohttp-client

~~We could set it to 2, but that will then remove some nested headers from the above sections, which is probably not desirable.~~
Setting it to 2 would eliminate some of the actual subsections shown currently.

**Comment by Dreamsorcerer** [comment]
Actually, I think that was caused by the previous Sphinx version bump, not related to this change.

**Pull request merged**
