### PR TITLE
Client session new args max_line_size and max_field_size

### PR DESCRIPTION
**Pull request by starflows**
## What do these changes do?

Add new arguments `max_line_size` and `max_field_size` to ClientSession.

## Are there changes in behavior for the user?

No, both arguments are optional and will use the same default values as previously when unset.

## Related issue number

https://github.com/aio-libs/aiohttp/issues/2304
https://github.com/aio-libs/aiohttp/issues/2988
https://github.com/aio-libs/aiohttp/issues/3862

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
I'll leave this one for @asvetlov to evaluate when he comes back. It looks like he has some kind of plan for this: https://github.com/aio-libs/aiohttp/issues/2304#issuecomment-335099602

But, #2988 and #3862 appear to be unrelated. They both refer to setting limits in an `Application` in regards to incoming requests.

**Comment by sumeshmurali** [comment]
Is this feature available to use?

**Comment by fili** [comment]
It looks like this is in the most recent codebase:

https://github.com/aio-libs/aiohttp/blob/bc37e44f233ab8f5ed543ba842b1a4866cd77252/aiohttp/client.py#L222

added using:

https://github.com/aio-libs/aiohttp/commit/ecd9c72697ca1529e7cae4693775612987a2a6d2

However, trying to use this leads to the following error: 

```
TypeError: ClientSession.__init__() got an unexpected keyword argument 'max_line_size'
```

And it is also missing from the official documentation:
https://docs.aiohttp.org/en/stable/_modules/aiohttp/client.html#ClientSession
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession

**Comment by Dreamsorcerer** [comment]
Ah, didn't notice the duplicate. There are tests in that code, so if you can change one to reproduce the failure and fix the problem, then we can merge it.

**Pull request closed without merging**
