### PR TITLE
Return 500 error when handler has wrong return type

### LINKED ISSUE #4572: Server closes connection if wrong type returned by handler
🐞 **Describe the bug**

Server closes session if handler returns anything else that `Response` instance.

💡 **To Reproduce**

```python
from aiohttp import web


async def handler(req):
    return 1

app = web.Application()
app.add_routes([web.get("/", handler)])
web.run_app(app)
```

```bash
~ curl localhost:8080
curl: (52) Empty reply from server
```

💡 **Expected behavior**

Error message in console and returned status 500.

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.1
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

Tested with aiohttp `3.6.2` and `master` branch fresh installations.

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Fixes #4572.

Not entirely sure if this is the best solution. Will sort the test tomorrow.

### CODE REVIEW

**Comment by webknjaz** [comment]
Perhaps, instead of returning a tuple, an exception wrapping the response could be raised and unwrapped/handled on the  calling side?

**Comment by Dreamsorcerer** [comment]
So, it's already covered by tests, they just asserted that the server would disconnect, which seems like an odd choice..

**Comment by Dreamsorcerer** [comment]
> Perhaps, instead of returning a tuple, an exception wrapping the response could be raised and unwrapped/handled on the calling side?

I don't think that works without more substantial refactoring. The actual writing happens in finish_response() where I create the replacement Response, the only reason I then return the new response, is because the calling function passes the resp to something else which accesses an attribute on it one more time, so I need it to replace the invalid resp object it passed in with the new one.

**Comment by Dreamsorcerer** [comment]
@webknjaz Backport's broken...

**Comment by webknjaz** [comment]
I know, GitHub's API response started including a new field which broke the mapping. I'll try to fix it today.

**Comment by Dreamsorcerer** [comment]
Oh, that's timeline as well. So, won't be able to merge anything new at the moment.

**Pull request merged**
