### PR TITLE
Update FUNDING.yml

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Am I good to add this?

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]
Absolutely! Should've done this long ago!

By the way, try registering @ https://thanks.dev — it's some new platform that Sentry uses to distribute funding. There been some weird changes in how they do it so maybe this'll get you something too (I haven't been able to figure out why they donated to me last year and reduced it this year, nor what projects they're using at all..)

**Comment by webknjaz** [comment]
Ah, I only now realized that I've been trying to keep the list sorted. But it's too late so maybe we'll fix that next time.

**Comment by Dreamsorcerer** [comment]
> By the way, try registering @ https://thanks.dev

Not sure what I'm doing wrong, but I just get an empty dashboard (2 days after signing up).

image

**Comment by webknjaz** [comment]
Same for me. I was hoping to track down what deps they see per request here https://twitter.com/chadwhitacre_/status/1710318405398470942, but haven't gotten anything so far.

**Comment by Dreamsorcerer** [comment]
The home page still looks like that, but it's finally updated and lists potential dependents now. I guess that means the project is atleast registered now and should be available for sponsors in the next round (I notice in the sponsor screen, half the projects are greyed out, probably because they aren't registered to accept payouts).

**Comment by webknjaz** [comment]
Yeah, I guess. They didn't get into much detail on Twitter. I also got my scanning finished yesterday..

**Comment by webknjaz** [comment]
I also don't understand if they want multiple separate users with own payout bank accounts or one account per project/org. I know that Tidelift does an account per person and spreads money equally or per arranged percentage..

**Comment by Dreamsorcerer** [comment]
Yeah, there is a button to book a call to talk about funding. Maybe worth doing that to ask them questions?

**Comment by Dreamsorcerer** [comment]
> Yeah, there is a button to book a call to talk about funding. Maybe worth doing that to ask them questions?

Oh, I just looked at the calendar times, and their hours are about 10pm till 9am in my timezone, which is a bit awkward.

**Comment by webknjaz** [comment]
I've just submitted like 4 of their feedback forms with stuff. Hopefully, they'll end up putting the answers into their FAQ...

**Comment by Dreamsorcerer** [comment]
Seems to be a few donations coming in now, not sure if you've figured out the details yet. I see payments being made to gh/aio-libs, but then it doesn't seem to have separate balances for gh/aio-libs and gh/dreamsorcerer or anything, which makes me think that the balance is in my account, but really not sure...

Also, I think you filled out the profile information under gh/aio-libs with your details. :P
There's a drop-down to switch between the different profiles.

**Comment by webknjaz** [comment]
> Also, I think you filled out the profile information under gh/aio-libs with your details. :P
> There's a drop-down to switch between the different profiles.

Yeah, by accident and never fixed it..

**Comment by webknjaz** [comment]
> I see payments being made to gh/aio-libs, but then it doesn't seem to have separate balances for gh/aio-libs and gh/dreamsorcerer or anything, which makes me think that the balance is in my account, but really not sure...

Oh, I got a reply by email and thought I shared it, but that was in some other conversation..
All the admins have access to the org account which is shared. It is possible to forward some of it into personal accounts. I also sent them a bug report about GH Sponsors UI bugs which they fixed as a result.. Here's that email:

**Comment by Dreamsorcerer** [comment]
Ah, OK, se we do still need to split it then.

Still a little confusing in the UI, as there's no dropdown or anything for the balance under the payouts page. So, if donations come through another account, it will surely be confusing to tell how much is in each account.

**Comment by webknjaz** [comment]
When you click on transfer or re-donate, it lets you select one of the balances. That's probably the only place in the UI where you see what's fully yours. And I also gave them the confusion feedback. They are pretty responsive so I encourage you to write them too so they understand the scale of the UX impact.

**Comment by webknjaz** [comment]
@Dreamsorcerer did you perform any transfers on thanks.dev on Nov 15? The UI has no way of tracking who performs what actions...

thanks-dev-nov-15-2023-payout

**Comment by Dreamsorcerer** [comment]
image

**Comment by Dreamsorcerer** [comment]
So, no, not me.

**Comment by webknjaz** [comment]
@Dreamsorcerer yeah, I saw the target, but I wasn't sure if that entry displays an actor. I think this is a transfer from the org account to a separate user account. Probably, Andrew did it, then. But I haven't talked to him in a while.

**Comment by webknjaz** [comment]
It has "to gh/<username>", and that "to" suggests the direction. I think anybody can forward money to other entities, just no idea how it'd look.

**Comment by Dreamsorcerer** [comment]
I was just going to leave it you to figure out what to do with it. I imagine he hasn't realised yet that it's a shared pool.

**Comment by webknjaz** [comment]
Maybe. I've been postponing this myself. And I think half a dozen org members have similar access too, by the way.

We probably need to implement this as a stopgap: https://github.com/typescript-eslint/.thanks.dev/blob/main/THANKS.yaml. It's an example they sent me via email.

**Comment by Dreamsorcerer** [comment]
Yeah, looks reasonable.

**Comment by webknjaz** [comment]
Looks like there's a per-repo config too: https://news.ycombinator.com/item?id=35521396. Although, that post suggests it's lower-cased. There's no docs or other resources on the internet related to this.

**Comment by webknjaz** [comment]
@Dreamsorcerer I also want to get more maintainers grab money from Tidelift: https://github.com/orgs/aio-libs/discussions/33.

**Pull request merged**
