### PR TITLE
Separate timeout errors (#7801)

### PR DESCRIPTION
**Pull request by atbuy**
## What do these changes do?

Separated Connection and Socket timeout errors, as requested in #7801

## Are there changes in behavior for the user?

There shouldn't be any change, since `ConnectionTimeoutError` and `SocketTimeoutError` both inherit from `ServerTimeoutError`, users can either catch in general `ServerTimeoutError`, or if they need to, they can now catch the specific timeouts.

## Related issue number

#7801 

## Checklist

- [X] I think the code is well written
- [X] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [X] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by atbuy** [comment]
Hey, can I add my username instead of my full name in `CONTRIBUTORS.txt`?

**Comment by Dreamsorcerer** [comment]
I suppose if we have separate timeouts, then maybe separate exceptions make sense.

**Comment by Dreamsorcerer** [comment]
If you could resolve the conflicts, then I'll get this merged.

**Comment by atbuy** [comment]
Thanks, I'll resolve them and ping you again.

**Comment by atbuy** [comment]
Hey, I fixed the conflicts and added a test for SocketTimeoutError.

**Comment by Dreamsorcerer** [comment]
If you could follow the backport instructions, that'd be great.

**Comment by atbuy** [comment]
I'll follow them. I wasn't sure if it was something I had to do or a maintainer.

**Comment by Dreamsorcerer** [comment]
Either, we're just a little busy currently.

**Pull request merged**
