### PR TITLE
[WIP] Complete chunked request on server eof

### LINKED ISSUE #5220: Server returns 400: "invalid character in chunk size header" for valid request
🐞 **Describe the bug**
When server ignores content of request with `Transfer-Encoding: chunked`, parsing of next request can fail.

💡 **To Reproduce**

The following script:

```
import asyncio

from aiohttp import web, ClientSession


async def start_server():
    async def hello(request):
        return web.Response(text="OK", status=200)

    app = web.Application()
    app.add_routes([web.get('/', hello)])
    app.add_routes([web.put('/', hello)])

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, 'localhost', 8080)
    await site.start()


async def main():
    await start_server()

    async def data_gen():
        for _ in range(10):
            yield b'just data'
            await asyncio.sleep(0.1)  # Make sending of content slow

    async with ClientSession() as session:
        while True:
            # Do put
            async with session.put("http://localhost:8080", data=data_gen()):
                pass
            # Do get
            async with session.get("http://localhost:8080") as resp:
                if resp.status != 200:
                    print("failed with status: ", resp.status)
                    print("content is: ", await resp.content.read())
                    return
            await asyncio.sleep(0.1)

asyncio.run(main())
```

Prints the following:

```
$ python3 reproduce.py 
Error handling request
Traceback (most recent call last):
  File ".../venv/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 315, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='invalid character in chunk size header'
failed with status:  400
content is:  b'invalid character in chunk size header'
```

If I add `await request.content.read()`, the problem disappears.

💡 **Expected behavior**

Server should not fail to parse valid request.

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.9
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.2
...
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
...
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.2
...
```

### PR DESCRIPTION
**Pull request by greshilov**
## What do these changes do?

Possible fix #5220  

Code is hacky and questionable, hope maintainers will help.

## Are there changes in behavior for the user?

No.

## Related issue number

#5220 

## Checklist

- [ ] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by luochen1990** [comment]
Hello， is this PR ready to be merged?

**Comment by Dreamsorcerer** [comment]
@greshilov Want to revive this PR?
From what I can tell from asevtlov's comment (https://github.com/aio-libs/aiohttp/issues/5220#issuecomment-732433418) this looks reasonable, just looks like we need something on the server side as well.

**Comment by thehesiod** [comment]
@alexmac this may prove interesting

**Comment by Dreamsorcerer** [comment]
Superseded by #7764 .

**Pull request closed without merging**
