### PR TITLE
Reduce WebSocket frame parser complexity

### PR DESCRIPTION
**Pull request by bdraco**
## What do these changes do?

Small improvement to reduce the WebSocket frame parser complexity

- Use identity checks instead of equality checks for the enums.  
- The length changes that trigger a break have been turned into guards to avoid all the indent to make a code a bit more readable. 
- The duplicate code in read payload length has been removed to improve maintainability

## Are there changes in behavior for the user?

no

## Is it a substantial burden for the maintainers to support this?

code is a bit easier to follow/maintain.

### CODE REVIEW

**Comment by bdraco** [comment]
running the profile shows the code is only 2-3% faster.  Thats within the margin of error.  The code is a lot easier to read now though.

I think we will have to cythonize like https://github.com/aio-libs/aiohttp/issues/2837 suggests to get more out of it

**Comment by bdraco** [comment]
`_feed_data` looks like it has more opportunities to optimize and cleanup

**Comment by Dreamsorcerer** [comment]
> I think we will have to cythonize like #2837 suggests to get more out of it

I'd really like to try throwing such code through mypyc first and seeing how that performs.

**Comment by bdraco** [comment]
Have you had good luck with mypyc in the past?  Its been a while since I tried it and wasn't able to ever use it in production because of stability issues.

**Comment by Dreamsorcerer** [comment]
> Have you had good luck with mypyc in the past? Its been a while since I tried it and wasn't able to ever use it in production because of stability issues.

Think it's only been considered stable for a couple of years, and was missing AsyncIterator support until around then. mypy itself seems to be stable, and I've used it for a few scripts, and in https://github.com/ruundii/bthidhub without further issues.

**Comment by bdraco** [comment]
Since the performance improvement is within the margin of error, I recharacterized this to be a code complexity reduction.

**Comment by Dreamsorcerer** [comment]
I'd probably skip the changelog myself, seems like no user-visible changes.

**Comment by Dreamsorcerer** [comment]
> > Have you had good luck with mypyc in the past? Its been a while since I tried it and wasn't able to ever use it in production because of stability issues.
> 
> Think it's only been considered stable for a couple of years, and was missing AsyncIterator support until around then. mypy itself seems to be stable, and I've used it for a few scripts, and in https://github.com/ruundii/bthidhub without further issues.

In short, even a couple of years ago, I didn't experience any stability issues personally, but didn't try it out on larger projects. The only issues were related to specific features, which were predictable. Things like AsyncIterator being missing resulted in some files not being able to compile, and there was atleast one case where the compiled code wouldn't work for some reason, along the lines of an inspection of a function needed to return that it was a function, but the compiled version is not considered a function by Python's inspect module, so was incompatible with the library code I was using.

**Comment by bdraco** [comment]
Thanks for the additional color.  I'll also ask for some recent feedback from Home Assistant devs to see if anyone has used it in a larger project.

**Comment by bdraco** [comment]
Marc pointed out that black is using `mypyc` https://ichard26.github.io/blog/2022/05/compiling-black-with-mypyc-part-1/ 

There are probably some gotchas we might hit based on that post, but its still probably easier than re-writing it in cython, although cython might be a bit faster.

**Comment by Dreamsorcerer** [comment]
Also, I think the main gotchas are to do with interacting with the object, e.g. mocking, inspecting etc. The code for parsers should be fairly private, so we shouldn't expect much user code to be interacting with it.

**Comment by bdraco** [comment]
It looks like it doesn't like the enums
```
% mypyc aiohttp/http_websocket.py
aiohttp/http_websocket.py:142: warning: Treating generator comprehension as list
aiohttp/http_websocket.py:163: warning: Treating generator comprehension as list
running build_ext
building 'aiohttp.http_websocket__mypyc' extension
clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/bdraco/aiohttp/venv/lib/python3.12/site-packages/mypyc/lib-rt -Ibuild -I/Users/bdraco/aiohttp/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c build/aiohttp/__native_http_websocket.c -o build/temp.macosx-14.0-arm64-cpython-312/build/aiohttp/__native_http_websocket.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-unused-but-set-variable -Wno-ignored-optimization-argument -Wno-cpp
build/aiohttp/__native_http_websocket.c:5182:16: error: use of undeclared identifier 'CPyStatic_WSParserState___READ_HEADER'
    cpy_r_r5 = CPyStatic_WSParserState___READ_HEADER;
               ^
build/aiohttp/__native_http_websocket.c:6131:17: error: use of undeclared identifier 'CPyStatic_WSMsgType___CLOSE'
    cpy_r_r31 = CPyStatic_WSMsgType___CLOSE;
                ^
build/aiohttp/__native_http_websocket.c:6274:17: error: use of undeclared identifier 'CPyStatic_WSCloseCode___PROTOCOL_ERROR'
    cpy_r_r68 = CPyStatic_WSCloseCode___PROTOCOL_ERROR;
                ^
build/aiohttp/__native_http_websocket.c:6371:17: error: use of undeclared identifier 'CPyStatic_WSCloseCode___INVALID_TEXT'
    cpy_r_r95 = CPyStatic_WSCloseCode___INVALID_TEXT;
                ^
build/aiohttp/__native_http_websocket.c:6424:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___CLOSE'
    cpy_r_r104 = CPyStatic_WSMsgType___CLOSE;
                 ^
build/aiohttp/__native_http_websocket.c:6476:18: error: use of undeclared identifier 'CPyStatic_WSCloseCode___PROTOCOL_ERROR'
    cpy_r_r116 = CPyStatic_WSCloseCode___PROTOCOL_ERROR;
                 ^
build/aiohttp/__native_http_websocket.c:6601:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___CLOSE'
    cpy_r_r159 = CPyStatic_WSMsgType___CLOSE;
                 ^
build/aiohttp/__native_http_websocket.c:6656:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___PING'
    cpy_r_r175 = CPyStatic_WSMsgType___PING;
                 ^
build/aiohttp/__native_http_websocket.c:6691:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___PING'
    cpy_r_r180 = CPyStatic_WSMsgType___PING;
                 ^
build/aiohttp/__native_http_websocket.c:6742:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___PONG'
    cpy_r_r194 = CPyStatic_WSMsgType___PONG;
                 ^
build/aiohttp/__native_http_websocket.c:6777:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___PONG'
    cpy_r_r199 = CPyStatic_WSMsgType___PONG;
                 ^
build/aiohttp/__native_http_websocket.c:6828:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___TEXT'
    cpy_r_r213 = CPyStatic_WSMsgType___TEXT;
                 ^
build/aiohttp/__native_http_websocket.c:6862:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___BINARY'
    cpy_r_r217 = CPyStatic_WSMsgType___BINARY;
                 ^
build/aiohttp/__native_http_websocket.c:6900:18: error: use of undeclared identifier 'CPyStatic_WSCloseCode___PROTOCOL_ERROR'
    cpy_r_r224 = CPyStatic_WSCloseCode___PROTOCOL_ERROR;
                 ^
build/aiohttp/__native_http_websocket.c:6978:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___CONTINUATION'
    cpy_r_r245 = CPyStatic_WSMsgType___CONTINUATION;
                 ^
build/aiohttp/__native_http_websocket.c:7059:18: error: use of undeclared identifier 'CPyStatic_WSCloseCode___MESSAGE_TOO_BIG'
    cpy_r_r268 = CPyStatic_WSCloseCode___MESSAGE_TOO_BIG;
                 ^
build/aiohttp/__native_http_websocket.c:7134:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___CONTINUATION'
    cpy_r_r287 = CPyStatic_WSMsgType___CONTINUATION;
                 ^
build/aiohttp/__native_http_websocket.c:7167:18: error: use of undeclared identifier 'CPyStatic_WSCloseCode___PROTOCOL_ERROR'
    cpy_r_r291 = CPyStatic_WSCloseCode___PROTOCOL_ERROR;
                 ^
build/aiohttp/__native_http_websocket.c:7221:18: error: use of undeclared identifier 'CPyStatic_WSMsgType___CONTINUATION'
    cpy_r_r304 = CPyStatic_WSMsgType___CONTINUATION;
                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by Dreamsorcerer** [comment]
Well, that's a disappointing start. If you can isolate a single part that causes the error, then I'd file a bug at https://github.com/mypyc/mypyc/issues

Maybe for immediate testing to get an idea of performance, we can just work around it (e.g. replace enum with ints).

**Comment by bdraco** [comment]
It looks like there is already an issue for the problem with IntEnum https://github.com/mypyc/mypyc/issues/1022

**Comment by bdraco** [comment]
Found one more back in 2020 https://github.com/mypyc/mypyc/issues/721

It doesn't look like it will get solved any time soon.

**Comment by bdraco** [comment]
`mypyc` is starting to feel like a dead end. I'm not sure its worth pursing. Maybe its best to move this forward as-is, and than I can look into optimizing `_feed_data` a bit since without resorting to mypyc or cython.

**Comment by Dreamsorcerer** [comment]
Yeah, mypyc/cython is a tangent, not related to this PR.

**Comment by Dreamsorcerer** [comment]
> It looks like there is already an issue for the problem with IntEnum [mypyc/mypyc#1022](https://github.com/mypyc/mypyc/issues/1022)

This one was just closed, so might be worth another try when the next mypy release is out..

**Comment by bdraco** [comment]
I'm relatively happy where we landed with this one as we don't have to maintain a separate pyx file for the WebSocketReader as the pxd turned out to be enough.  Would be nice to give mypyc another shot for the next project that comes up that could benefit from it.

**Pull request merged**
