### PR TITLE
Upgrade to llhttp 9.1.3

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@cdce8p Can I give you atleast triager permissions on aiohttp? You've been pretty helpful recently.

**Comment by cdce8p** [comment]
> @cdce8p Can I give you atleast triager permissions on aiohttp? You've been pretty helpful recently.

If you like, sure! Just tbh I don't yet know how much I'll be able to contribute to aiohttp in the future. I mostly started working on it for the Python 3.12 update.

**Comment by Dreamsorcerer** [comment]
Yep, understood. That should give you access to manage issues etc. If you do contribute more, then maybe I'll ask to invite you for commit access later.

**Comment by cdce8p** [comment]
> Yep, understood. That should give you access to manage issues etc. If you do contribute more, then maybe I'll ask to invite you for commit access later.

Works for me!

--
For the `3.9` release: Is there anything I can help with left?

**Comment by Dreamsorcerer** [comment]
Not right now, trying to coordinate with @webknjaz for a release. Hopefully he'll have some time soon.

**Comment by davfsa** [comment]
@Dreamsorcerer Just wanted to say, thanks for the great and quick work pushing aiohttp to work with 3.12!

Just wanted to bring into your radar (in case it wasnt already) that yarl will also need a release with 3.12 wheels, as the current release will fail with cython errors :)

**Comment by cdce8p** [comment]
> Just wanted to bring into your radar (in case it wasnt already) that yarl will also need a release with 3.12 wheels, as the current release will fail with cython errors :)

Are you sure about that? I can build / install it without issues for Python 3.12.

**Comment by davfsa** [comment]
> Are you sure about that? I can build / install it without issues for Python 3.12.

Oh, it does seem to be fixed. Last time I tested this was in a beta version for 3.12, so i assume some stuff got fixed since then. All good then, sorry for generating noise :sweat_smile:

**Pull request merged**
