### PR TITLE
Release v3.9.4

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Preparing for tomorrow, let me know if there's any reason to delay. @bdraco @webknjaz

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]
LGTM

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
https://github.com/aio-libs/aiohttp/issues/8184 might be ready tomorrow but its not a regression and its been a problem for a while so no need to wait for it

**Comment by Dreamsorcerer** [comment]
> #8184 might be ready tomorrow but its not a regression and its been a problem for a while so no need to wait for it

Probably a good one to have in, not sure if we want to do any more 3.9 release after this. I'll do the release later in the week if you need time to finish it.

**Comment by bdraco** [comment]
I was hoping to get a thumbs up from the op on if it fixed it for his user before moving it forward. I'll write the tests for it tomorrow regardless, since I'll be time poor at the end of the week as I have family in town.

**Comment by webknjaz** [comment]
> I was hoping to get a thumbs up from the op on if it fixed it for his user before moving it forward.

@bdraco did you get that info?

**Comment by Dreamsorcerer** [comment]
That one's merged now. We've had a couple of other last minute bug reports we've been fixing, but I think we're good for me to proceed with a release tomorrow.

**Comment by webknjaz** [comment]
Sounds good!

**Pull request merged**
