### PR TITLE
Add separate non-blocking start_app corountine

### LINKED ISSUE #5386: Separated start corountine
🐣 **Is your feature request related to a problem? Please describe.**

I want to start an `aiohttp.web.Application` non-blockingly so that I can continue executing some lines.

💡 **Describe the solution you'd like**

I looked into it and the perfect solution would be to rename the internal `_run_app` corountine to `start_app` and then move the infinite while loop that sleeps into the `run_app` function.

❓ **Describe alternatives you've considered**

Well for my use-case I've considered copying the body of the both functions and removing the logic that makes the function blocking.

📋 **Additional context**

I've tried to fix it, but I get this:
```
aiohttp/web.py: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x aiohttp/web.py`
  If it is supposed to be executable, double-check its shebang.
````
(I am using Windows WSL)

I already fixed the issue. But can't commit anything (I do pass all other tests). Here is the changed/important parts of the file:
```py
async def start_app(
    app: Union[Application, Awaitable[Application]],
    *,
    host: Optional[Union[str, HostSequence]] = None,
    port: Optional[int] = None,
    path: Optional[str] = None,
    sock: Optional[socket.socket] = None,
    shutdown_timeout: float = 60.0,
    keepalive_timeout: float = 75.0,
    ssl_context: Optional[SSLContext] = None,
    print: Optional[Callable[..., None]] = print,
    backlog: int = 128,
    access_log_class: Type[AbstractAccessLogger] = AccessLogger,
    access_log_format: str = AccessLogger.LOG_FORMAT,
    access_log: Optional[logging.Logger] = access_logger,
    handle_signals: bool = True,
    reuse_address: Optional[bool] = None,
    reuse_port: Optional[bool] = None,
) -> AppRunner:
    """Start an app locally.

    Use `run_app` if you do not wish to control and keep the the event loop
    alive yourself, this is non-blocking and returns the runner.
    """
    if asyncio.iscoroutine(app):
        app = await app  # type: ignore

    app = cast(Application, app)

    runner = AppRunner(
        app,
        handle_signals=handle_signals,
        access_log_class=access_log_class,
        access_log_format=access_log_format,
        access_log=access_log,
        keepalive_timeout=keepalive_timeout,
    )

    await runner.setup()

    sites = []  # type: List[BaseSite]

    if host is not None:
        if isinstance(host, (str, bytes, bytearray, memoryview)):
            sites.append(
                TCPSite(
                    runner,
                    host,
                    port,
                    shutdown_timeout=shutdown_timeout,
                    ssl_context=ssl_context,
                    backlog=backlog,
                    reuse_address=reuse_address,
                    reuse_port=reuse_port,
                )
            )
        else:
            for h in host:
                sites.append(
                    TCPSite(
                        runner,
                        h,
                        port,
                        shutdown_timeout=shutdown_timeout,
                        ssl_context=ssl_context,
                        backlog=backlog,
                        reuse_address=reuse_address,
                        reuse_port=reuse_port,
                    )
                )
    elif path is None and sock is None or port is not None:
        sites.append(
            TCPSite(
                runner,
                port=port,
                shutdown_timeout=shutdown_timeout,
                ssl_context=ssl_context,
                backlog=backlog,
                reuse_address=reuse_address,
                reuse_port=reuse_port,
            )
        )

    if path is not None:
        if isinstance(path, (str, bytes, bytearray, memoryview)):
            sites.append(
                UnixSite(
                    runner,
                    path,
                    shutdown_timeout=shutdown_timeout,
                    ssl_context=ssl_context,
                    backlog=backlog,
                )
            )
        else:
            for p in path:
                sites.append(
                    UnixSite(
                        runner,
                        p,
                        shutdown_timeout=shutdown_timeout,
                        ssl_context=ssl_context,
                        backlog=backlog,
                    )
                )

    if sock is not None:
        if not isinstance(sock, Iterable):
            sites.append(
                SockSite(
                    runner,
                    sock,
                    shutdown_timeout=shutdown_timeout,
                    ssl_context=ssl_context,
                    backlog=backlog,
                )
            )
        else:
            for s in sock:
                sites.append(
                    SockSite(
                        runner,
                        s,
                        shutdown_timeout=shutdown_timeout,
                        ssl_context=ssl_context,
                        backlog=backlog,
                    )
                )
    for site in sites:
        await site.start()

    if print:  # pragma: no branch
        names = sorted(str(s.name) for s in runner.sites)
        print(
            "======== Running on {} ========\n"
            "(Press CTRL+C to quit)".format(", ".join(names))
        )

    return runner


def _cancel_tasks(
    to_cancel: Set["asyncio.Task[Any]"], loop: asyncio.AbstractEventLoop
) -> None:
    if not to_cancel:
        return

    for task in to_cancel:
        task.cancel()

    loop.run_until_complete(
        asyncio.gather(*to_cancel, loop=loop, return_exceptions=True)
    )

    for task in to_cancel:
        if task.cancelled():
            continue
        if task.exception() is not None:
            loop.call_exception_handler(
                {
                    "message": "unhandled exception during asyncio.run() shutdown",
                    "exception": task.exception(),
                    "task": task,
                }
            )


def run_app(
    app: Union[Application, Awaitable[Application]],
    *,
    debug: bool = False,
    host: Optional[Union[str, HostSequence]] = None,
    port: Optional[int] = None,
    path: Optional[str] = None,
    sock: Optional[socket.socket] = None,
    shutdown_timeout: float = 60.0,
    keepalive_timeout: float = 75.0,
    ssl_context: Optional[SSLContext] = None,
    print: Optional[Callable[..., None]] = print,
    backlog: int = 128,
    access_log_class: Type[AbstractAccessLogger] = AccessLogger,
    access_log_format: str = AccessLogger.LOG_FORMAT,
    access_log: Optional[logging.Logger] = access_logger,
    handle_signals: bool = True,
    reuse_address: Optional[bool] = None,
    reuse_port: Optional[bool] = None,
) -> None:
    """Run an app locally,

    Use `start_app` if you wish to control and keep the event loop
    alive yourself.
    """
    loop = asyncio.get_event_loop()
    loop.set_debug(debug)

    # Configure if and only if in debugging mode and using the default logger
    if loop.get_debug() and access_log and access_log.name == "aiohttp.access":
        if access_log.level == logging.NOTSET:
            access_log.setLevel(logging.DEBUG)
        if not access_log.hasHandlers():
            access_log.addHandler(logging.StreamHandler())

    try:

        async def _run_app():
            try:
                runner = await start_app(
                    app,
                    host=host,
                    port=port,
                    path=path,
                    sock=sock,
                    shutdown_timeout=shutdown_timeout,
                    keepalive_timeout=keepalive_timeout,
                    ssl_context=ssl_context,
                    print=print,
                    backlog=backlog,
                    access_log_class=access_log_class,
                    access_log_format=access_log_format,
                    access_log=access_log,
                    handle_signals=handle_signals,
                    reuse_address=reuse_address,
                    reuse_port=reuse_port,
                )

                # sleep forever by 1 hour intervals,
                # on Windows before Python 3.8 wake up every 1 second to handle
                # Ctrl+C smoothly
                if sys.platform == "win32" and sys.version_info < (3, 8):
                    delay = 1
                else:
                    delay = 3600

                while True:
                    await asyncio.sleep(delay)
            finally:
                await runner.cleanup()

        main_task = loop.create_task(_run_app())
        loop.run_until_complete(main_task)
    except (GracefulExit, KeyboardInterrupt):  # pragma: no cover
        pass
    finally:
        _cancel_tasks({main_task}, loop)
        _cancel_tasks(asyncio.all_tasks(loop), loop)
        loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()
        asyncio.set_event_loop(None)
```
As to not make this issue too big I've pasted the entire file (if needed) on Mystbin: https://mystb.in/HalloweenPreferenceReunion.sql

I would open a pull request if I could, what can be done about this?

### PR DESCRIPTION
**Pull request by Bluenix2**
## What do these changes do?
This will add a separate start corountine allowing the user to use a similar half-performant function as `run_app` but if they wish to do the keepalive sleeps themselves.

## Are there changes in behavior for the user?

This has 0 breaking changes, unless someone depends on the previous `_run_app` function which was renamed to `stat_app` and had the keepalive code moved.
## Related issue number

This should close #5386, which I opened confused about the pre-commit hooks failing.
## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

> - Unit tests for the changes exist

If there is for `run_app` then I guess? I did not add any new unit tests for the new `start_app` function.

> The format is &lt;Name&gt; &lt;Surname&gt;.

I do not want to reveal my real name, looking at the document it doesn't seem as if any aliases are there so I am not gonna add myself there. Which is completely fine by me.

> Please keep alphabetical order, the file is sorted by names.

Not possible considering `run_app` is dependent on `start_app` which means an exception to that rule is made here.

### CODE REVIEW

**Comment by BluePhoenixGame** [comment]
So the issue with the latest run is that it raises an error. Meaning that `start_app` fails, which in turn means that `runner` doesn't get defined, which in turn means that when the Python interpreter goes to run `await runner.cleanup()` it fails.
```
ERROR    asyncio:base_events.py:1738 unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-2748' coro=<run_app.<locals>.main_runner() done, defined at /home/runner/work/aiohttp/aiohttp/aiohttp/web.py:488> exception=UnboundLocalError("local variable 'runner' referenced before assignment")>
Traceback (most recent call last):
  File "/home/runner/work/aiohttp/aiohttp/aiohttp/web.py", line 490, in main_runner
    runner = await start_app(
  File "/home/runner/work/aiohttp/aiohttp/aiohttp/web.py", line 415, in start_app
    await site.start()
  File "/home/runner/work/aiohttp/aiohttp/aiohttp/web_runner.py", line 127, in start
    self._server = await loop.create_server(
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/unittest/mock.py", line 1093, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/unittest/mock.py", line 1097, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/unittest/mock.py", line 1152, in _execute_mock_call
    raise effect
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/aiohttp/aiohttp/aiohttp/web.py", line 524, in run_app
    loop.run_until_complete(main_task)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/runner/work/aiohttp/aiohttp/aiohttp/web.py", line 520, in main_runner
    await runner.cleanup()
UnboundLocalError: local variable 'runner' referenced before assignment
```

I can't reproduce it, this is how I tested my code:
```py
import asyncio
from aiohttp import web

routes = web.RouteTableDef()

@routes.get('/')
async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes(routes)

async def main():
    try:
        runner = await web.start_app(app)
        while True:
            await asyncio.sleep(1)
    finally:
        await runner.cleanup()

asyncio.run(main())
```
*This obviously doesn't show the use case this is satisfying, you normally would use `run_app` here*

**Comment by Bluenix2** [comment]
Okay, I finally found a nice implementation which passes all unit tests. See #5389 as to why some checks get canceled.

Regarding codecov I am not sure, the code it complains about is just code I simply moved? I also don't have any experience writing any new unit tests if that is needed.

**Comment by Rixxan** [comment]
I see this PR was closed without being merged - was that intentional and this PR is no longer in development or did this simply slip through the cracks?

**Comment by Bluenix2** [comment]
I closed this because I was fighting the tests - not exactly sure how I would structure the code to make them pass - and later on re-structured my code to no longer need the added function. I intentionally closed this PR and I am not working on it.

**Pull request closed without merging**
