### PR TITLE
Pin down multidict

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
With the new errors coming in, it might be a good idea to pin this down in the 3.8 release.

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
LGTM, I like the idea.

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
@Dreamsorcerer this probably needs a change note, though.

**Comment by Dreamsorcerer** [comment]
Looks like it is already affecting some others. Maybe make a new 3.8 release tomorrow to minimise the impact?

**Comment by asvetlov** [comment]
multidict 6.0.2 should fix problems.
Sorry for the inconvinience.

**Comment by jakob-keller** [comment]
aiohttp 3.8.2 was just released and it restricts the multidict dependency to >=4.5,<6.0. Is this still intended?

**Comment by hugovk** [comment]
@jakob-keller Please see PR https://github.com/aio-libs/aiohttp/pull/6950 to re-bump it.

**Pull request merged**
