### PR TITLE
Patchback/backports/3.9/f90cb1952c272936845b93a8f424b32e703d545c/pr 6843

### PR DESCRIPTION
**Pull request by SamirPS**
## What do these changes do?

I modify the web.py file and add Union[str,pathlib.Path] for path

## Are there changes in behavior for the user?

For the option of path, we can have str or pathlib.path

## Related issue number

#6839 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Think you might have messed up the conflicts, this appears to only include the test changes and nothing else.

**Comment by SamirPS** [comment]
weird i will check the 28 july

**Comment by SamirPS** [comment]
I delete the branch and redo the things you tell me @Dreamsorcerer  i didn't know it's will close the pull requests

**Comment by SamirPS** [comment]
@Dreamsorcerer ??

**Comment by Dreamsorcerer** [comment]
Did you create a new PR? You can just repush your local branch.

**Comment by SamirPS** [comment]
The branch : Patchback/backports/3.9/f90cb1952c272936845b93a8f424b32e703d545c/pr-6843 exist on my github

**Comment by webknjaz** [comment]
Try opening a PR with that branch then.

**Pull request closed without merging**
