### PR TITLE
Feature/expose request interface

### PR DESCRIPTION
**Pull request by jujumilk3**
## What do these changes do?
Display ClientSession methods' parameters in the help window.

Before
image
After
image

## Are there changes in behavior for the user?
Yes

## Related issue number
https://github.com/aio-libs/aiohttp/issues/7185

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
I don't think we want so much copy/paste.

I think there is a better alterative coming up though: https://peps.python.org/pep-0692/
Seems we'll need to wait until Python 3.12 to use it.

**Comment by dzhalaevd** [comment]
> I don't think we want so much copy/paste.
> 
> I think there is a better alterative coming up though: https://peps.python.org/pep-0692/ Seems we'll need to wait until Python 3.12 to use it.

I think it may not be necessary to wait for version 3.12, as precise type annotations for **kwargs are now supported using TypedDict starting from MyPy version 0.981 (https://github.com/python/mypy/pull/13471). This means that **kwargs: Any can now be rewritten as **kwargs: Unpack[HttpClientRequest], for example.

We need to update `mypy` to 0.981 and create possibly `types.py` which will contain our custom types

Here is an example that works on python 3.10
```python
import sys
from typing import (
    Any,
    Optional,
    TypedDict,
    Union
)

if sys.version_info >= (3, 11):
    from typing import (  # noqa: F401
        Unpack,
    )
else:
    from typing_extensions import (  # noqa: F401
        Unpack,
    )

StrOrURL = Union[str, bytes, "URL"]


class HttpClientRequest(TypedDict):
    data: Optional[Union[str, bytes, dict]]
    json: Optional[Union[dict, list]]
    cookies: Optional[dict[str, str]]
    headers: Optional[dict[str, str]]
    allow_redirects: Optional[bool]


def get(url: StrOrURL, *, allow_redirects: bool = True, **kwargs: Unpack[HttpClientRequest]) -> Any:
    """
    A function that sends an HTTP GET request.

    :param url: The URL to send the request to.
    :param allow_redirects: Whether or not to follow redirects.
    :param kwargs: Additional parameters to pass to the request.
    :return: The response from the server.
    """


# Example usage
param = {"data": None, "json": None, "cookies": None, "headers": None, "allow_redirects": True}
get(url="https://example.com", **param)

get(url="https://example.com", allow_redirects=True, data=None, json=None)
```

**Comment by Dreamsorcerer** [comment]
> > I don't think we want so much copy/paste.
> > I think there is a better alterative coming up though: https://peps.python.org/pep-0692/ Seems we'll need to wait until Python 3.12 to use it.
> 
> I think it may not be necessary to wait for version 3.12, as precise type annotations for **kwargs are now supported using TypedDict starting from MyPy version 0.981 ([python/mypy#13471](https://github.com/python/mypy/pull/13471)). This means that **kwargs: Any can now be rewritten as **kwargs: Unpack[HttpClientRequest], for example.

That is PEP 692. It's still not stable and disabled by default (https://github.com/python/mypy/issues/14697) and requires Unpack from Python 3.12. We can use typing_extensions if needed, but would be nice to start dropping typing_extensions as a dependency if possible. So, I'd probably still wait till 3.12 is released, though we can start preparing a PR beforehand if anyone wants to start looking at it.

**Comment by Dreamsorcerer** [comment]
This has been done with Unpack now.

**Pull request closed without merging**
