### PR TITLE
[PR #8445 backport][3.9] Fixes read_timeout on WS connection not respecting ws_connect's timeouts #8444

### PR DESCRIPTION
**Pull request by arcivanov**
Please see #8445 for the source PR

### CODE REVIEW

**Comment by bdraco** [comment]
The bot will auto-create backport PRs (assuming there are no conflicts) from https://github.com/aio-libs/aiohttp/pull/8445 once it merges since its tagged with the backport tags.

**Comment by arcivanov** [comment]
@bdraco there will be major conflicts ass the API changed (`ClientWSTimeout` introduced in master)

**Comment by Dreamsorcerer** [comment]
> @bdraco there will be major conflicts as the API changed (`ClientWSTimeout` introduced in master vs 3.9)

Yes, but it's preferable to follow our normal backport procedure to ensure everything lines up with cherry picking etc. (for example, this needs to backport to 3.10 first).

**Comment by bdraco** [comment]
3.9 is no longer getting backports. I'm going to close this one since we are going to do a 3.10 release soon

**Pull request closed without merging**
