### PR TITLE
Update copyright year from 2020 to 2022

### PR DESCRIPTION
**Pull request by meitham**
## What do these changes do?
A simple update to copyright year from 2020 to 2022

## Are there changes in behavior for the user?
No change in behaviour, but simply giving the docs reader a sense that the project is up-to-date.  

## Related issue number
None

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by webknjaz** [comment]
It's better to drop the years or just keep the first one.

**Comment by Dreamsorcerer** [comment]
> It's better to drop the years or just keep the first one.

I think from a legal perspective, this range is technically correct. Copyright is from the date the code was written, so this says parts of the project are copyrighted in 2013, 2014, ..., and 2022. Although it is a bit of a hassle needing to keep it updated..

**Comment by meitham** [comment]
> It's better to drop the years or just keep the first one.

I saw a discussion recently on HN around dropping the copyright year but I'm failing to find the link.  The copyright year came in a discussion around picking up a Python web framework and it was pointed that aiohttp might not be as maintained as FastAPI purely based on the date in that copyright notice!

**Comment by webknjaz** [comment]
> I think from a legal perspective, this range is technically correct.

Not exactly. Copyright is associated with the year of content creation and remains valid throughout the future years. When the content is updated, there's some part of the content that is new so this update copyright gets a new year. The copyright is held by the author regardless of the statement in the files. That line can make it easier to track it but is not really required. It only creates maintenance burden.

Here's a good guidance to follow https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/. Plus there's Hynek's note at https://hynek.me/til/copyright-years/.

**Comment by Dreamsorcerer** [comment]
Yep, exactly. I think this is the technically more accurate approach. But, I think removing the years altogether makes sense, so I'd vote for that.

**Comment by meitham** [comment]
> > I think from a legal perspective, this range is technically correct.
> 
> Not exactly. Copyright is associated with the year of content creation and remains valid throughout the future years. When the content is updated, there's some part of the content that is new so this update copyright gets a new year. The copyright is held by the author regardless of the statement in the files. That line can make it easier to track it but is not really required. It only creates maintenance burden.
> 
> Here's a good guidance to follow https://www.linuxfoundation.org/blog/copyright-notices-in-open-source-software-projects/. Plus there's Hynek's note at https://hynek.me/til/copyright-years/.

Thanks, yes it was Hynek's post on HN that I have failed to find earlier.  I have now removed the years from the copyright notice.

**Comment by webknjaz** [comment]
Yeah, I suggested to add that LF post to the article when he posted it on Twitter :) This is how I remembered where to look.

**Comment by webknjaz** [comment]
@meitham while on it, could you update the text to "aio-libs contributors"? It seems weird that they are different.

**Comment by meitham** [comment]
> aio-libs contributors"

done

**Review by webknjaz — APPROVED** [review]
Brilliant, thanks!

**Review by CryptoGodfatherVA2 — COMMENTED** [review]
Yes

**Pull request merged**
