### PR TITLE
Http exception cookies support

### PR DESCRIPTION
**Pull request by derlih**
## What do these changes do?

Add methods `set_cookie()` an `del_cookie()` to `HTTPException`
Add `cookies` property to `HTTPException`

## Are there changes in behavior for the user?

User can set the cookies for `HTTPException`

## Related issue number

#4277 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by derlih** [comment]
@asvetlov if this approach is OK, I will update the documentation.

**Review by asvetlov — COMMENTED** [review]
Looks good.
Could you please update web_excetions.rst to reflect new methods?

**Comment by derlih** [comment]
What `versionadded` should I use to reflect these changes in documentation?

**Comment by asvetlov** [comment]
4.0
In 3.x branch HTTPException is derived from Response, thus it has cookie methods already.
Let's add breaking changes in major releases only.

**Comment by derlih** [comment]
That was exactly the reason why I've raised my question. If it doesn't break the API from 3.x  in theory it can be backported to 3.x.

**Comment by asvetlov** [comment]
Dropping the inheritance from `web.Response` is not backward compatible change.

While we keep the inheritance -- there Is no need to backport this PR because `web.Response` already provides the cookies API

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
