### PR TITLE
Fix Read The Docs config

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by webknjaz** [comment]
What was broken?

**Comment by Dreamsorcerer** [comment]
Wrong version of ssl. Seems it needs the OS set explicitly to the latest version (maybe that `build: latest` is a setting that has been removed?).

**Comment by webknjaz** [comment]
Oh, that's because urllib3 v2 is finally out (and unpinned!)
Fair enough..

**Comment by Dreamsorcerer** [comment]
Also, did you disable the admin bypass for branch protection recently? I wouldn't care, but the CI currently always waits 30 mins for the Windows test to timeout and fail before it merges things..

**Comment by webknjaz** [comment]
I think I did at some point. OTOH, you shouldn't have to babysit the CI if you use automerge. If the windows jobs time out and you know what a typical success timeline looks like, I'd recommend setting that timeout for said jobs to improve responsiveness..

**Comment by Dreamsorcerer** [comment]
It's just the 3.11 broken one. While the Mac one fails quickly, the Windows one has a test which takes 5 mins to timeout (and then retries that failed test).

**Pull request merged**
