### PR TITLE
Support SSL param for aiohttp.request(ssl=*)

### PR DESCRIPTION
**Pull request by zhombie**
## What do these changes do?

Supports ssl param for asyncio.request(ssl=*) method, which is handy attribute, otherwise you have to create session and after you can request call

## Are there changes in behavior for the user?

Old way:
```python
async with aiohttp.ClientSession() as session:
    response = await session.get(url='<any url>', ssl=True or False)
    ...
```

New way:
```python
async with aiohttp.request('<http method>', url='<any url>', ssl=True or False) as response:
    ...
```

## Related issue number

I could not find any issue, that's why created PR immediately

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Review by webknjaz — COMMENTED** [review]
This PR needs tests and a change note per https://github.com/aio-libs/aiohttp/tree/master/CHANGES#readme.

**Comment by webknjaz** [comment]
> asyncio.request(ssl=*)

Also, did you mean aiohttp?

**Comment by zhombie** [comment]
> > asyncio.request(ssl=*)
> 
> Also, did you mean aiohttp?

Oops, yeap. I have edited the issue title

**Comment by zhombie** [comment]
> This PR needs tests and a change note per https://github.com/aio-libs/aiohttp/tree/master/CHANGES#readme.

Sorry, but now I have no time to do your requests, maybe later

**Comment by webknjaz** [comment]
> > This PR needs tests and a change note per [`master`/CHANGES#readme](https://github.com/aio-libs/aiohttp/tree/master/CHANGES?rgh-link-date=2021-11-03T12%3A27%3A44Z#readme).
> 
> Sorry, but now I have no time to do your requests, maybe later

Okay, we'll wait, then. There's a branch protection check that blocks PRs from being merged unless a changelog fragment is present.

**Comment by Dreamsorcerer** [comment]
This appears to already be done now.

**Pull request closed without merging**
