### PR TITLE
Release v3.8.4

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
@webknjaz So, squash commit this into 3.8, add a tag, then merge commit to 3.9?

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Is tools/cleanup_changes.py needed for anything?

**Comment by webknjaz** [comment]
s/0.8.4/3.8.4/ tho

**Comment by webknjaz** [comment]
> So, squash commit this into 3.8, add a tag, then merge commit to 3.9?

Yes, and follow up with another post-dev bump.

**Comment by webknjaz** [comment]
> Is tools/cleanup_changes.py needed for anything?

I don't think I ever used it. I think only Andrew did.

**Comment by webknjaz** [comment]
I just checked that script and it seems it attempts emulate fragment removal but this should usually happen with `git merge` if done properly.

**Comment by Dreamsorcerer** [comment]
> s/0.8.4/3.8.4/ tho

Ha, fortunately only the commit message, wiped out with the squash commit.

**Comment by webknjaz** [comment]
@Dreamsorcerer remember to do a post-release bump, plus merge 3.8 into 3.9 locally, and 3.9 into master, after that. You'll probably have to deal with conflict resolutions and there's a chance of accidentally reintroducing removed things, because the merge could be complex. So I'd recommend inspecting said merge commit and amending it as necessary before pushing. You could also push to a temporary branch to see the CI status and then, fast-forward the real one to the tested commit.

**Comment by Dreamsorcerer** [comment]
I've run git merge locally, but that doesn't delete the fragments. I'm not sure why it would actually, because the files were added in separate branches, so they don't have a common history..

**Comment by Dreamsorcerer** [comment]
That script seems to work though, and seems to have found a few that were missed from some previous releases:
```
rm 'CHANGES/5901.bugfix'
rm 'CHANGES/6189.bugfix'
rm 'CHANGES/6195.bugfix'
rm 'CHANGES/6201.bugfix'
rm 'CHANGES/6205.misc'
rm 'CHANGES/6240.doc'
rm 'CHANGES/6276.doc'
rm 'CHANGES/6278.doc'
rm 'CHANGES/6305.bugfix'
rm 'CHANGES/6638.bugfix'
rm 'CHANGES/7180.bugfix'
```
Also README.rst, so that needs to be fixed atleast.

**Comment by webknjaz** [comment]
> I'm not sure why it would actually, because the files were added in separate branches, so they don't have a common history..

Typically, it'd track those when the cherry-pick comment is preserved. FWIW you can delete them with that script and amend.

**Comment by Dreamsorcerer** [comment]
OK, all done.

**Pull request merged**
