### PR TITLE
Ensure websocket transport is closed when client does not close it (#8200)

### PR DESCRIPTION
**Pull request by bdraco**
(cherry picked from commit 6ec4747a02955dbf227fb66f4419d124a37fcc71)

### CODE REVIEW

**Comment by bdraco** [comment]
That import time test running with coverage on is a bit useless since coverage is so much slower on 3.12

**Comment by Dreamsorcerer** [comment]
> That import time test running with coverage on is a bit useless since coverage is so much slower on 3.12

Ah, so it's the coverage that is causing it to fail? Is there a way to run a test without coverage or something?

**Comment by bdraco** [comment]
I was going to mark it `@pytest.mark.no_cover` but than I realized its just cpython 3.12 taking more time to import which is expected here. Maybe we should increase the time if its > 3.12 instead

**Comment by Dreamsorcerer** [comment]
> nevermind, its running isolated. Its a regression in cpython 3.12 taking longer to import

Do we reckon it'll get improved in a future release?

**Comment by Dreamsorcerer** [comment]
> Maybe we should increase the time if its > 3.12 instead

Can do, or we can skip it on 3.12 for now, if we think it's a temporary regression.

**Comment by bdraco** [comment]
> > nevermind, its running isolated. Its a regression in cpython 3.12 taking longer to import
> 
> Do we reckon it'll get improved in a future release?

It might be better in 3.13, but from what I gather the timing changes are expected in 3.12 as there were trade-offs to make other things at run time faster

**Comment by bdraco** [comment]
some more backstory https://github.com/python/cpython/issues/90081

**Comment by Dreamsorcerer** [comment]
Well, if coverage is going to affect the performance, we should disable it. That test will have no impact on coverage anyway as it does nothing more than import the library. If that makes a notable difference, then we may want to lower the threshold to match the new timings.

If there is a regression in 3.12 we should probably just skip the test on 3.12. If there's still an issue on 3.13, then we can reevaluate.

**Pull request merged**
