### PR TITLE
Release v3.8.2

### PR DESCRIPTION
**Pull request by webknjaz**
## What do these changes do?

This is a release preparation for v3.8.2.

## Are there changes in behavior for the user?

The sdist will be buildable under Python 3.11. Wheels for Python 3.11 built with rc2 are going to be available.

## Related issue number

N/A

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Appears to be an open backport #6540. Though it may only be updating a test.

I'd also like to see #6889 included, if there's no objections to that.

**Comment by webknjaz** [comment]
@Dreamsorcerer may I get an approval for this changelog? One item that I'm not sure about is py3.5. Technically, it's not an API change and pip handles it very well these days. So it's probably fine that it's backported into a patch release. Plus the default wheel building setup doesn't produce those wheels anymore anyway.
I wanted to make the last release of the 3.8.x stream with minimal changes and forget about this branch. WDYT?

Potential release workflow is at https://github.com/aio-libs/aiohttp/actions/runs/3089216983. It'll need to be approved too.

**Comment by Dreamsorcerer** [comment]
> One item that I'm not sure about is py3.5.

Seems fine to me, 3.5 is long dead, and 3.6 is already unsupported (and removed from the aiohttp 3.9 release).

> I wanted to make the last release of the 3.8.x stream with minimal changes and forget about this branch. WDYT?

Seems fine, but possible we might need it for an emergency fix or similar until 3.9 is ready for release.

**Comment by webknjaz** [comment]
> Appears to be an open backport #6540. Though it may only be updating a test.

Looks like I've fixed that test already, the rest are formatting changes. Plus there's conflicts.

**Comment by webknjaz** [comment]
> I'd also like to see #6889 included, if there's no objections to that.

That seems straightforward, will do.

**Comment by webknjaz** [comment]
I double-checked stuff from https://github.com/aio-libs/aiohttp/issues?q=is%3Aopen+label%3Abackport-3.8+sort%3Aupdated-desc and it doesn't seem like there's anything else that could be included. Plus, they all need a newer backport label now.

**Comment by webknjaz** [comment]
> I'd also like to see #6889 included, if there's no objections to that.

Backported.

**Comment by webknjaz** [comment]
~New release attempt: https://github.com/aio-libs/aiohttp/actions/runs/3090829504.~ Will have to wait for the CI resources to free up, then an approval will be needed before publishing.

**Comment by webknjaz** [comment]
> ~New release attempt: [aio-libs/aiohttp/actions/runs/3090829504](https://github.com/aio-libs/aiohttp/actions/runs/3090829504).~ Will have to wait for the CI resources to free up, then an approval will be needed before publishing.

~New attempt: https://github.com/aio-libs/aiohttp/actions/runs/3091013580~

**Comment by webknjaz** [comment]
Seems like GHA hits GH's rate limits and jobs fail on fetching the Git repo. It'll need some restarts to succeed.

**Comment by webknjaz** [comment]
> ~New attempt: [aio-libs/aiohttp/actions/runs/3091013580](https://github.com/aio-libs/aiohttp/actions/runs/3091013580)~

~Hopefully, the final one: https://github.com/aio-libs/aiohttp/actions/runs/3092629710~

**Comment by webknjaz** [comment]
Just approved https://github.com/aio-libs/aiohttp/actions/runs/3092629710/jobs/5006137559. ~15 min to go.

**Comment by webknjaz** [comment]
> ValueError: Version check mismatch: 3.8.1 != 3.8.2

:man_facepalming:

**Comment by webknjaz** [comment]
> ~Hopefully, the final one: [aio-libs/aiohttp/actions/runs/3092629710](https://github.com/aio-libs/aiohttp/actions/runs/3092629710)~

Here we go again: https://github.com/aio-libs/aiohttp/actions/runs/3093922036.

**Pull request merged**
