### PR TITLE
Turn RawResponseMessage into a NamedTuple

### PR DESCRIPTION
**Pull request by Gobot1234**
## What do these changes do?

This makes pyright happier when accessing the fields on the class 

## Are there changes in behavior for the user?

No complaints from pyright with regards to it thinking the fields are unknown.

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Review by Dreamsorcerer — APPROVED** [review]

**Comment by Gobot1234** [comment]
Does this change need a news entry?

**Comment by Dreamsorcerer** [comment]
A short .misc entry would be great. But, I was mainly waiting for you to mark the PR as ready.

**Comment by webknjaz** [comment]
@Dreamsorcerer looks like you pulled in the entire PR template into the merged commit message. How did that happen?

**Comment by Dreamsorcerer** [comment]
Ah, I think that's the default, should we change the default?
In the settings it is set to "Default to pull request title and description"

**Pull request merged**
